info:
    name: K Means Program Demo
    version: 0.1
    data_flow_model: groupby_aggergate
    iterative: true
    kernel_type: cuda
    py_c_extention: true
sources:
    python: python_funcs.py
    cpp: kmeans_module.cpp
    header: kmeans.h
    cuda: kmeans.cu
code: {}
