info:
    # NOTE: for best results, run with threshold set to 0.0000001
    name: K-Means
    version: 0.1
    py_c_extention: true
sources:
    python: python_funcs.py
    cpp: kmeans_module.cpp
    header: kmeans.h
    cuda: kmeans.cu
code: {}
