info:
    # NOTE: for best results, run with threshold set to 0.0000001
    name: K-Means
    version: 0.1
    py_c_extention: false
sources:
    python: python_funcs.py
    header: program.h
    cuda: kernel.cu
code: {}
